services:
  php:
    container_name: ${PROJECT_NAME}-php
    image: ${PROJECT_NAME}-app:dev
    build:
      context: .
      target: php
    restart: unless-stopped
    environment:
      ENVIRONMENT: development
      PUID: ${DOCKER_UID:-1000}
      PGID: ${DOCKER_GID:-1000}
      REDIRECT_URI: http://localhost:8099
      CLIENT_ID: YOUR_CLIENT_ID
      CLIENT_SECRET: YOUR_CLIENT_SECRET
      REALM: YOUR_REALM
      PUBLIC_KEYCLOAK_URL: http://localhost:8080
      INTERNAL_KEYCLOAK_URL: ''
    working_dir: /var/www/html-composer/auth-client
    volumes:
      - ./examples/app:/var/www/html
      - ./examples:/var/www/html-examples
      - ./:/var/www/html-composer/auth-client
      - ./frontend/dist:/var/www/html/public/frontend
      - ./docker/php:/container/custom
    ports:
      - ${DOCKER_PROJECT_IP:-127.0.0.1}:8099:80
  node:
    container_name: ${PROJECT_NAME}-node
    image: neunerlei/node-nginx:25
    restart: unless-stopped
    environment:
      ENVIRONMENT: development
      PUID: ${DOCKER_UID:-1000}
      PGID: ${DOCKER_GID:-1000}
      NODE_WORKER_COMMAND: "npm run watch"
    volumes:
      - './frontend/:/var/www/html'
      - './docker/node:/container/custom'
